### PR TITLE
Study

### PR DESCRIPTION
**Pull request by Casbah1911**
Learning to clone

### CODE REVIEW

**Comment by KingPrice** [comment]
hey are you in IS 1003 at UTSA CasBah?

**Comment by Casbah1911** [comment]
Yes

Sent from my iPhone

On Sep 11, 2020, at 1:42 PM, KingPrice <notifications@github.com> wrote:

﻿

hey are you in IS 1003 at UTSA CasBah?

**Comment by Gothamv** [comment]
Hey guys! Hope you're finding this tutorial useful. May I know how did you come across this article?

**Comment by Casbah1911** [comment]
Hi there, my instructor from UTSA suggested as a good resource to learn the 5 basic commands of GIT.

Thank you for making it.

Casbah

Sent from my iPhone

On Sep 12, 2020, at 1:13 AM, Gowtham Venkatesan <notifications@github.com> wrote:

﻿

Hey guys! Hope you're finding this tutorial useful. May I know how did you come across this article?

**Comment by Gothamv** [comment]
Oh, that's cool!

**Pull request merged**
